### PR TITLE
Backends selection support + PID1 process reaper + Alpine semver handling

### PR DESCRIPTION
**Pull request by leleobhz**
Hello!

I want to merge following features

* Backends selection support: By using [sane-backends](https://pkgs.alpinelinux.org/packages?name=sane-backends&branch=edge&repo=&arch=&maintainer=) package and handling dll.d and dll.conf it's possible to pick at runtime backends user want to saned to want come up
* PID1 process reaper: Adding [catatonit](https://github.com/openSUSE/catatonit) to container allow signal to be properly handled by saned when signal was sent by docker (docker rm as example).
* saned without inetd: inetd was not necessary since saned can listen directly leading to a lighter resource usage
* Alpine version handling: Since Alpine Linux adopt [semantic versioning](https://wiki.alpinelinux.org/wiki/Package_policies), it's trusteable that same major and minor version will keep compatibility and release version will bring fixes that does not break compatibility. This is important to allow image to has latest security fixes without compromise stability. 

Also, I've enabled actions in my repo, so you can try it at ghcr.io/leleobhz/sane:latest

Can this PR be merged? 

Thanks!

### CODE REVIEW

**Comment by fpiesche** [comment]
This is excellent, thank you very much!

**Comment by leleobhz** [comment]
Hello @fpiesche 

I changed my PR to alpine 3.19.1 as you used too.

**Comment by fpiesche** [comment]
Sorry this took a while - we got caught up in a house move which ate a lot of my energy for the past few months. Finally returning to some normality here...

**Comment by leleobhz** [comment]
> Sorry this took a while - we got caught up in a house move which ate a lot of my energy for the past few months. Finally returning to some normality here...

Hello @fpiesche 

Great you have your moving done sucessfully (At least as possible :P) 

Thank you so much for you attention! Have nice day!

**Pull request merged**
